# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Laradok < Formula
  desc "A terminal UI for managing Laravel apps inside Docker, locally or over SSH"
  homepage "https://laradok.babintsev.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexbabintsev/laradok/releases/download/v0.1.0/laradok_0.1.0_darwin_amd64.tar.gz"
      sha256 "a92275642f416c7f336e572f65d5c3e99ce9b4d0165b417937829c1af283b74c"

      define_method(:install) do
        bin.install "laradok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexbabintsev/laradok/releases/download/v0.1.0/laradok_0.1.0_darwin_arm64.tar.gz"
      sha256 "a4aeb233afa36e6626b748a80f3bbe78b4b4c5b580e76696b2853d558e2c803b"

      define_method(:install) do
        bin.install "laradok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexbabintsev/laradok/releases/download/v0.1.0/laradok_0.1.0_linux_amd64.tar.gz"
      sha256 "61426454368de9c6df59bb0d98cf8b22685153744217a2448a59b49e7c2c121c"
      define_method(:install) do
        bin.install "laradok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexbabintsev/laradok/releases/download/v0.1.0/laradok_0.1.0_linux_arm64.tar.gz"
      sha256 "cd78c1a201b3c5cca2b7f905870dd9c0cc75638378db5c6fe3f74294c1d175a2"
      define_method(:install) do
        bin.install "laradok"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/laradok --version")
  end
end
